// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAdm.API.Data;

namespace ProAdm.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220724201956_MigrationPrincipal")]
    partial class MigrationPrincipal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ProAdm.API.Models.Abastecimento", b =>
                {
                    b.Property<int>("AbastecimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Convenio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("KmAbastecimento")
                        .HasColumnType("INTEGER");

                    b.Property<float>("LitrosAbastecimento")
                        .HasColumnType("REAL");

                    b.Property<int?>("ResponsavelPolicialId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saldo")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAbastecimento")
                        .HasColumnType("REAL");

                    b.Property<int?>("ViaturaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AbastecimentoId");

                    b.HasIndex("ResponsavelPolicialId");

                    b.HasIndex("ViaturaId");

                    b.ToTable("Abastecimentos");
                });

            modelBuilder.Entity("ProAdm.API.Models.Policial", b =>
                {
                    b.Property<int>("PolicialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostoGraduacao")
                        .HasColumnType("TEXT");

                    b.HasKey("PolicialId");

                    b.ToTable("Policiais");
                });

            modelBuilder.Entity("ProAdm.API.Models.Viatura", b =>
                {
                    b.Property<int>("ViaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Odometro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefixo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCombustivel")
                        .HasColumnType("TEXT");

                    b.HasKey("ViaturaId");

                    b.ToTable("Viaturas");
                });

            modelBuilder.Entity("ProAdm.API.Models.Abastecimento", b =>
                {
                    b.HasOne("ProAdm.API.Models.Policial", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelPolicialId");

                    b.HasOne("ProAdm.API.Models.Viatura", "Viatura")
                        .WithMany()
                        .HasForeignKey("ViaturaId");

                    b.Navigation("Responsavel");

                    b.Navigation("Viatura");
                });
#pragma warning restore 612, 618
        }
    }
}
