// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAdm.API.Data;

namespace ProAdm.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220719014113_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ProAdm.API.Models.Viatura", b =>
                {
                    b.Property<int>("ViaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Combustivel")
                        .HasColumnType("TEXT");

                    b.Property<int>("Odometro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefixo")
                        .HasColumnType("TEXT");

                    b.HasKey("ViaturaId");

                    b.ToTable("Viaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
