// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAdm.Persistence;

namespace ProAdm.Persistence.Migrations
{
    [DbContext(typeof(ProAdmContext))]
    partial class ProAdmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ProAdm.Domain.Abastecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Convenio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbastecimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("KmAbastecimento")
                        .HasColumnType("INTEGER");

                    b.Property<float>("LitrosAbastecimento")
                        .HasColumnType("REAL");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saldo")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorAbastecimento")
                        .HasColumnType("REAL");

                    b.Property<int?>("ViaturaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("ViaturaId");

                    b.ToTable("Abastecimentos");
                });

            modelBuilder.Entity("ProAdm.Domain.Servidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostoGraduacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("ProAdm.Domain.Viatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Odometro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefixo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCombustivel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Viaturas");
                });

            modelBuilder.Entity("ProAdm.Domain.Abastecimento", b =>
                {
                    b.HasOne("ProAdm.Domain.Servidor", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.HasOne("ProAdm.Domain.Viatura", "Viatura")
                        .WithMany()
                        .HasForeignKey("ViaturaId");

                    b.Navigation("Responsavel");

                    b.Navigation("Viatura");
                });
#pragma warning restore 612, 618
        }
    }
}
